import { Product } from './types';

const PHONE_MODELS = [
  'iPhone 12/12pro',
  'iPhone 12promax',
  'iPhone 13/14',
  'iPhone 13pro',
  'iPhone 13promax',
  'iPhone 14plus/15plus',
  'iPhone 14pro',
  'iPhone 14promax',
  'iPhone 15',
  'iPhone 15promax',
  'iPhone 16',
  'iPhone 16plus',
  'iPhone 16pro',
  'iPhone 16promax',
  'iPhone 17',
  'iPhone 17air',
  'iPhone 17pro',
  'iPhone 17promax',
];

export const sampleProducts: Omit<Product, '_id'>[] = [
  {
    productId: 1,
    name: 'Long Sleeve Graphic Tee',
    slug: 'long-sleeve-graphic-tee',
    description: 'Long sleeve graphic tee with unique design. Perfect for layering or standalone wear.',
    price: 150,
    images: ['/images/products/tops-01.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: true,
  },
  {
    productId: 2,
    name: 'Green Snake Tee',
    slug: 'green-snake-tee',
    description: 'Bold snake graphic tee in green. Stand out with this statement piece.',
    price: 120,
    images: ['/images/products/tops-02.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Green'],
    inStock: true,
    featured: false,
  },
  {
    productId: 3,
    name: 'Back Print Tee',
    slug: 'back-print-tee',
    description: 'Classic tee with eye-catching back print. Minimalist front, bold back.',
    price: 130,
    images: ['/images/products/tops-03.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 4,
    name: 'White Graphic Tee',
    slug: 'white-graphic-tee',
    description: 'Clean white tee with artistic graphic print. Versatile streetwear essential.',
    price: 110,
    images: ['/images/products/tops-04.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White'],
    inStock: true,
    featured: false,
  },
  {
    productId: 5,
    name: 'Culture Cap',
    slug: 'culture-cap',
    description: 'Classic black cap with bold graphic arabic word print. A timeless streetwear staple.',
    price: 60,
    images: ['/images/products/caps-02.jpeg'],
    collection: 'caps',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 6,
    name: '5 Panel Cap Culture',
    slug: '5-panel-cap-culture',
    description: '5-panel cream cap featuring the word "Culture Shock" in a striking graphic design. Perfect for adding an urban edge to any outfit.',
    price: 80,
    images: ['/images/products/caps-01.jpeg'],
    collection: 'caps',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Cream'],
    inStock: true,
    featured: false,
  },
  {
    productId: 7,
    name: 'Culture X Kejora Sling Bag Knitted Handmade',
    slug: 'culture-x-kejora-sling-bag-knitted-handmade',
    description: 'Handmade knitted sling bag featuring the "Culture X Kejora" design. A unique accessory for your everyday wear.',
    price: 120,
    images: ['/images/products/sling-bags-01.jpeg'],
    collection: 'bags',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black', 'Grey'],
    inStock: true,
    featured: false,
  },
  {
    productId: 8,
    name: 'Cultushock x Mutu Case (Kejutan Budaya)',
    slug: 'culture-x-mutu-case-kejutan-budaya',
    description: 'Lindungi telefon kau dengan gaya yang penuh makna. Case eksklusif kolaborasi Cultushock x Mutu menampilkan reka bentuk "Kejutan Budaya" — perpaduan seni jalanan tempatan dengan identiti budaya yang kuat. Bahan berkualiti tinggi, ketepatan potongan sempurna untuk setiap model iPhone.',
    price: 55,
    images: ['/images/products/case-01.png'],
    collection: 'cases',
    category: 'accessories',
    sizes: PHONE_MODELS,
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 9,
    name: 'Cultushock x Mutu Case (Putar Belit)',
    slug: 'culture-x-mutu-case-putar-belit',
    description: 'Case kolaborasi Cultushock x Mutu dengan motif "Putar Belit" — reka bentuk yang mencabar perspektif dan mencerminkan keberanian bersuara melalui seni. Warna krim yang elegan dipasangkan dengan grafik berani yang menjadi pernyataan tersendiri.',
    price: 55,
    images: ['/images/products/case-02.png'],
    collection: 'cases',
    category: 'accessories',
    sizes: PHONE_MODELS,
    colors: ['Cream'],
    inStock: true,
    featured: false,
  },
  {
    productId: 10,
    name: 'Cultushock x Mutu Case (Shock)',
    slug: 'culture-x-mutu-case-shock',
    description: 'The "Shock" edition — case terhad Cultushock x Mutu yang hadir dalam warna ungu eksklusif. Terinspirasi daripada kejutan budaya yang menggegarkan, reka bentuk ini melambangkan keberanian untuk tampil beza dan meninggalkan kesan.',
    price: 60,
    images: ['/images/products/case-03.png'],
    collection: 'cases',
    category: 'accessories',
    sizes: PHONE_MODELS,
    colors: ['Purple'],
    inStock: true,
    featured: false,
  },
];