import { Product } from './types';

export const sampleProducts: Omit<Product, '_id'>[] = [
  {
    productId: 1,
    name: 'Long Sleeve Graphic Tee',
    slug: 'long-sleeve-graphic-tee',
    description: 'Long sleeve graphic tee with unique design. Perfect for layering or standalone wear.',
    price: 150,
    images: ['/images/products/tops-01.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: true,
  },
  {
    productId: 2,
    name: 'Green Snake Tee',
    slug: 'green-snake-tee',
    description: 'Bold snake graphic tee in green. Stand out with this statement piece.',
    price: 120,
    images: ['/images/products/tops-02.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Green'],
    inStock: true,
    featured: false,
  },
  {
    productId: 3,
    name: 'Back Print Tee',
    slug: 'back-print-tee',
    description: 'Classic tee with eye-catching back print. Minimalist front, bold back.',
    price: 130,
    images: ['/images/products/tops-03.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 4,
    name: 'White Graphic Tee',
    slug: 'white-graphic-tee',
    description: 'Clean white tee with artistic graphic print. Versatile streetwear essential.',
    price: 110,
    images: ['/images/products/tops-04.jpg'],
    collection: 'tops',
    category: 'streetwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White'],
    inStock: true,
    featured: false,
  },
  {
    productId: 5,
    name: 'Culture Cap',
    slug: 'culture-cap',
    description: 'Classic black cap with bold graphic arabic word print. A timeless streetwear staple.',
    price: 60,
    images: ['/images/products/caps-02.jpeg'],
    collection: 'caps',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 6,
    name: '5 Panel Cap Culture',
    slug: '5-panel-cap-culture',
    description: '5-panel cream cap featuring the word "Culture Shock" in a striking graphic design. Perfect for adding an urban edge to any outfit.',
    price: 80,
    images: ['/images/products/caps-01.jpeg'],
    collection: 'caps',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Cream'],
    inStock: true,
    featured: false,
  },
  {
    productId: 7,
    name: 'Culture X Kejora Sling Bag Knitted Handmade',
    slug: 'culture-x-kejora-sling-bag-knitted-handmade',
    description: 'Handmade knitted sling bag featuring the "Culture X Kejora" design. A unique accessory for your everyday wear.',
    price: 120,
    images: ['/images/products/sling-bags-01.jpeg'],
    collection: 'bags',
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black', 'Grey'],
    inStock: true,
    featured: false,
  }
];