import { Product } from './types';

export const sampleProducts: Omit<Product, '_id'>[] = [
  {
    productId: 1,
    name: 'Long Sleeve Graphic Tee',
    slug: 'long-sleeve-graphic-tee',
    description: 'Long sleeve graphic tee with unique design. Perfect for layering or standalone wear.',
    price: 150,
    images: ['/images/products/tops-01.jpg'],
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: true,
  },
  {
    productId: 2,
    name: 'Green Snake Tee',
    slug: 'green-snake-tee',
    description: 'Bold snake graphic tee in green. Stand out with this statement piece.',
    price: 120,
    images: ['/images/products/tops-02.jpg'],
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Green'],
    inStock: true,
    featured: false,
  },
  {
    productId: 3,
    name: 'Back Print Tee',
    slug: 'back-print-tee',
    description: 'Classic tee with eye-catching back print. Minimalist front, bold back.',
    price: 130,
    images: ['/images/products/tops-03.jpg'],
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    inStock: true,
    featured: false,
  },
  {
    productId: 4,
    name: 'White Graphic Tee',
    slug: 'white-graphic-tee',
    description: 'Clean white tee with artistic graphic print. Versatile streetwear essential.',
    price: 110,
    images: ['/images/products/tops-04.jpg'],
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White'],
    inStock: true,
    featured: false,
  },
];